server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelmix: true
      lowpass: true
      compression: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

logging:
  level:
    root: INFO
    lavalink: INFO
